### ISSUE TITLE
MacOS install problem

### ISSUE THREAD

**Issue by micro128390** [LoopPerfect/rxterm#3]
$ **uname -a**
Darwin d-p155-213 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ **mkdir -p junk/abc && cd junk/abc**

$ **buckaroo quickstart**
Files modified (5):
 * Wrote /Users/micro128390/junk/abc/buckaroo.json
 * Touched /Users/micro128390/junk/abc/.buckconfig
 * Wrote /Users/micro128390/junk/abc/BUCKAROO_DEPS
 * Wrote /Users/micro128390/junk/abc/abc/apps/main.cpp
 * Wrote /Users/micro128390/junk/abc/BUCK
buck run :main

$ **buckaroo install github+loopperfect/rxterm**
Read the project file.
Stats: 2s 0kb 2 events
java.lang.IllegalArgumentException: Multiple entries with same key: 0.0.1.0=GitCommitHash{d4bfff0f6d2b346a16ccd0ed21bc4fec9239cab5} and 0.0.1.0=GitCommitHash{d4bfff0f6d2b346a16ccd0ed21bc4fec9239cab5}
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at com.google.common.collect.CollectCollectors$$Lambda$203/1759095866.apply(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:503)
	at com.loopperfect.buckaroo.sources.GitProviderRecipeSource.lambda$fetch$15(GitProviderRecipeSource.java:112)
	at com.loopperfect.buckaroo.sources.GitProviderRecipeSource$$Lambda$186/550676690.apply(Unknown Source)
	at com.loopperfect.buckaroo.Process$2.lambda$subscribe$2(Process.java:247)
	at com.loopperfect.buckaroo.Process$2$$Lambda$147/238331210.run(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onComplete(LambdaObserver.java:87)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:60)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:63)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:37)
	at io.reactivex.Single.subscribe(Single.java:2703)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
	at io.reactivex.Single.subscribe(Single.java:2703)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at com.loopperfect.buckaroo.Process$2.subscribe(Process.java:229)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext.subscribeActual(ObservableOnErrorNext.java:38)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at com.loopperfect.buckaroo.Process$2.subscribe(Process.java:229)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at io.reactivex.Observable.subscribe(Observable.java:10788)
	at com.loopperfect.buckaroo.Process$2.lambda$subscribe$2(Process.java:248)
	at com.loopperfect.buckaroo.Process$2$$Lambda$147/238331210.run(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onComplete(LambdaObserver.java:87)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:60)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:63)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:2703)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
	at io.reactivex.Single.subscribe(Single.java:2703)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at com.loopperfect.buckaroo.Process$2.subscribe(Process.java:229)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at com.loopperfect.buckaroo.Process.lambda$merge$20(Process.java:374)
	at com.loopperfect.buckaroo.Process$$Lambda$173/1380505945.subscribe(Unknown Source)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at com.loopperfect.buckaroo.Process$2.subscribe(Process.java:229)
	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:10842)
	at io.reactivex.Observable.subscribe(Observable.java:10828)
	at io.reactivex.Observable.subscribe(Observable.java:10788)
	at com.loopperfect.buckaroo.Process$2.lambda$subscribe$2(Process.java:248)
	at com.loopperfect.buckaroo.Process$2$$Lambda$147/238331210.run(Unknown Source)
	at io.reactivex.internal.observers.LambdaObserver.onComplete(LambdaObserver.java:87)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onComplete(ObservableOnErrorNext.java:115)
	at io.reactivex.internal.observers.BasicFuseableObserver.onComplete(BasicFuseableObserver.java:119)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:430)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onComplete(ObservableConcatMap.java:517)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onSuccess(SingleToObservable.java:60)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:63)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:37)
	at io.reactivex.Single.subscribe(Single.java:2703)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
...

**Comment by nikhedonia** [comment]
It works now.
Turns out there where two tags pointing to the same commit with conflicting version numbers and that confused buckaroo.
